OCS_APP/urls.py
from django.urls import path
from OCS_APP import views

app_name = 'OCS_APP'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/', views.category_list_view, name='category-list'),
    path('category/<cid>/', views.category_products_list_view, name='category-product-list'),
    path('product/<pid>/', views.product_detail_view, name='product-detail'),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('search/', views.search_view, name='search'),
    path('cart/', views.cart_view, name='cart'),
    path('delete-from-cart/', views.delete_item_from_cart, name='delete-from-cart'),
    path('update-cart/', views.update_cart, name='update-cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('payment-completed/<inv_id>/<pay_method>/', views.payment_completed_view, name='payment-completed'),
    path('payment-failed/', views.payment_failed_view, name='payment-failed'),
    path('dashboard/', views.customer_dashboard, name='dashboard'),
    path('dashboard/order/<int:id>', views.order_detail, name='order-detail'),
    path('contact-us/', views.contact_us, name='contact-us'),
    path('products/tag/<slug:tag_slug>/', views.tag_list, name='tags'),
    path('make-default-address/', views.make_address_default, name='make-default-address'),
    path('delete-address/', views.delete_address, name='delete-address'),
    path('shop/', views.shop_view, name='shop'),
    path('add-review/<int:pid>/', views.ajax_add_review, name='add-review'),
    
    path('my/', views.my, name='my'),
]

handler404 = 'OCS_APP.views.custom_404_view'

Oral_Care_Solution/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('OCS_APP.urls')),
    path('user/', include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path('log-in/', views.login_view, name='log-in'),
    path('log-out/', views.logout_view, name='log-out'),
    path('register/', views.register_view, name='register'),
    path('profile/update/', views.profile_update, name='profile-update'),
    path('forget-password/', views.forgot_password, name='forgot_password'),
    path('get-reset-password-email/', views.get_reset_password_email, name='get_reset_password_email'),
    path('reset/<str:uidb64>/<str:token>/', views.reset_password, name='reset_password'),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    User_Email = models.EmailField(unique=True)
    username = models.CharField(max_length=50)
    USERNAME_FIELD = 'User_Email'
    REQUIRED_FIELDS = ['username']
    def __str__(self):
        return self.username
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    image = models.ImageField(upload_to="image", blank = True)
    full_name = models.CharField(max_length = 50, null = True, blank = True)
    bio = models.CharField(max_length = 200, blank = True)
    phone = models.CharField(max_length=14, blank = True)
    verified = models.BooleanField(default = False)
    
    def __str__(self):
        return self.full_name

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    User_Email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Email'}), error_messages={'unique':'This email address is already in use. Please choose a different one.'})
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))
    
    class Meta:
        model = User
        fields = [
            'username',
            'User_Email'
        ]

class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(label='Full Name', widget=forms.TextInput(attrs={'placeholder':'Full Name'}))
    bio = forms.CharField(label='Bio', widget=forms.TextInput(attrs={'placeholder':'Bio'}))
    phone = forms.CharField(label='Phone', widget=forms.TextInput(attrs={'placeholder':'Phone'}))
    image = forms.ImageField()
    class Meta:
        model = Profile
        fields = ['full_name', 'image', 'bio', 'phone']

userauths/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from userauths.forms import UserRegisterForm, ProfileForm
from userauths.models import User, Profile
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.utils.encoding import force_bytes
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.http import JsonResponse

#User = settings.AUTH_USER_MODEL

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form .is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Hey {username}, Your account is created successfully.')
            new_user = authenticate(username = form.cleaned_data['User_Email'], password = form.cleaned_data['password1'])
            login(request, new_user)
            Profile.objects.create(user = request.user, full_name = username)
            return redirect('OCS_APP:index')
    else:
        form = UserRegisterForm()
    context = {
        'form':form
    }
    return render(request, 'userauths/register.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login_view(request):
    if request.user.is_authenticated:
        return redirect('OCS_APP:index')
    if request.method == "POST":
        User_Email = request.POST.get('email')
        password = request.POST.get('password')
        try:
            user = User.objects.get(User_Email=User_Email)
            user = authenticate(request, User_Email = User_Email, password = password)
            if user is not None:
                login(request, user)
                messages.success(request, 'You are logged in.')
                return redirect('OCS_APP:index')
            else:
                messages.warning(request, 'Invalid email or password. Please try again.')
        except:
            messages.warning(request, 'Invalid email or password. Please try again.')
    return render(request, 'userauths/log-in.html')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def logout_view(request):
    request.session.flush()
    logout(request)
    messages.success(request, 'You have logged out.')
    return redirect('userauths:log-in')

@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def profile_update(request):
    profile = Profile.objects.get(user = request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance = profile)
        if form.is_valid():
            new_form = form.save(commit = False)
            new_form.user = request.user
            new_form.save()
            u = User.objects.get(username = request.user.username)
            u.username = form.cleaned_data['full_name']
            u.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('OCS_APP:dashboard')
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'userauths/profile-edit.html', {'form':form, 'profile':profile})

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def forgot_password(request):
    return render(request, 'userauths/forgot_password.html')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def get_reset_password_email(request):
    email = request.GET.get('email')
    user = User.objects.filter(email=email).first()
    if user is not None:
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        reset_link = f"http://127.0.0.1:8000/user/reset/{str(uid)}/{str(token)}/"
        send_mail('Password reset request', f'Click the following link to reset your password: {reset_link}', 'aliahmedchamp@gmail.com', [email], fail_silently=False)
        return JsonResponse({'correct':True})
    else:
        return JsonResponse({'incorrect':False})

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def reset_password(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            password = request.POST.get('password')
            confirm_password = request.POST.get('confirm_password')
            if password != confirm_password:
                messages.warning(request, 'Passwords do not match.')
                return render(request, 'userauths/password_reset_form.html')
            user.set_password(password)
            user.save()
            messages.success(request, 'Your password has been successfully reset.')
            return redirect('userauths:log-in')
        else:
            return render(request, 'userauths/password_reset_form.html', {'uidb64': uidb64, 'token': token})
    else:
        return render(request, 'userauths/password_reset_invalid.html')

templates/userauths/forgot_password.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main pages">
    <div class="page-header breadcrumb-wrap">
		<div class="container">
			<div class="breadcrumb">
				<a href="{% url 'OCS_APP:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
				<span></span> Login <span></span> Forget Password
			</div>
		</div>
	</div>

    <div class="page-content pt-60 pb-60  d-flex justify-content-center align-items-center">
        <div class="card text-center" style="width: 300px;">
            <div class="card-header h5 text-white bg-primary">Password Reset</div>
            <div class="card-body px-5">
                <p class="card-text py-2">
                    Enter your email address and we'll send you an email with instructions to reset your password.
                </p>
                <div class="form-outline">
                    <input type="email" class="form-control my-3 reset-myemail" placeholder="Your Email *" name="reset-myemail">
                </div>
                    <button class="btn btn-primary w-100 reset-email" style="border: none;">Reset password</button>
                <div class="d-flex justify-content-between mt-4">
                    <a class="" href="{% url 'userauths:log-in' %}">Login</a>
                    <a class="" href="{% url 'userauths:register' %}">Register</a>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/userauths/log-in.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main pages">
	<div class="page-header breadcrumb-wrap">
		<div class="container">
			<div class="breadcrumb">
				<a href="{% url 'OCS_APP:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
				<span></span> Login
			</div>
		</div>
	</div>

	<div class="page-content pt-60 pb-60">
		<div class="container">
			<div class="row">
				<div class="col-xl-8 col-lg-10 col-md-12 m-auto">
					<div class="row">
						<div class="col-lg-6 pr-30 d-none d-lg-block" style="text-align: center;">
							<img class="border-radius-15" src="{% static 'assets/imgs/theme/OCS.png' %}" alt="" />
		<!--					<div class="card-login" style="position: relative; right: 13px; border: none;">
								<a href="#" class="social-login facebook-login">
									<img src="{% static 'assets/imgs/theme/icons/logo-facebook.svg' %}" alt="" />
									<span style="font-size: 18.5px;">Login with Facebook</span>
								</a>
								<a href="#" class="social-login google-login" style="border: 1px solid #7E7E7E;">
									<img src="{% static 'assets/imgs/theme/icons/logo-google.svg' %}" alt="" />
									<span>Login with Google</span>
								</a>
							</div>-->
						</div>
						<div class="col-lg-6 col-md-8">
							<div class="login_wrap widget-taber-content background-white">
								<div class="padding_eight_all bg-white">
									<div class="heading_s1">
										<h1 class="mb-5">Login</h1>
										<p class="mb-30">Don't have an account? <a href="{% url 'userauths:register' %}">Create here</a></p>
									</div>
									<form method="POST">
										{% csrf_token %}
										<div class="form-group">
											<input type="text" required name="email" placeholder="Your Email Address *" />
										</div>
										<div class="form-group">
											<input required type="password" name="password" placeholder="Your password *" />
										</div>
										<div class="login_footer form-group mb-20">
											<div class="chek-form"></div>
											<a class="text-muted" href="{% url 'userauths:forgot_password' %}">Forgot password?</a>
										</div>
										<div class="form-group mb-30">
											<button type="submit" class="btn btn-heading btn-block hover-up" name="login">Log in</button>
										</div>
								<!--	<div class="form-group social-login-buttons">
											<a href="#" class="social-login facebook-login" style="background-color: #1877F2;">
												<img src="{% static 'assets/imgs/theme/icons/logo-facebook.svg' %}" alt="Facebook Logo" />
												<span style="color: #fff;">Login with Facebook</span>
											</a>
											<a href="#" class="social-login google-login">
												<img src="{% static 'assets/imgs/theme/icons/logo-google.svg' %}" alt="Google Logo" />
												<span>Login with Google</span>
											</a>
										</div>	-->	
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>  

{% endblock content %}

templates/userauths/password_reset_form.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main pages">
    <div class="page-header breadcrumb-wrap">
		<div class="container">
			<div class="breadcrumb">
				<a href="{% url 'OCS_APP:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
				<span></span> Login <span></span> Forget Password
			</div>
		</div>
	</div>
    
    <div class="page-content pt-60 pb-60 d-flex justify-content-center align-items-center">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-sm-8 text-center">
                    <h1>Password Reset</h1>
                </div>
            </div>
            <div class="row justify-content-center align-items-center">
                <div class="col-sm-4">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group pass_show"> 
                            <input type="password" class="form-control" placeholder="New Password" id="id_password" name="password"> 
                        </div>  
                        <div class="form-group pass_show"> 
                            <input type="password" class="form-control" placeholder="Confirm Password" id="id_confirm_password" name="confirm_password"> 
                        </div>
                        <button type="submit" class="btn btn-primary">Reset Password</button>
                    </form>
                </div>
                <div class="col-sm-4">
                    <img src="{% static 'assets/imgs/page/reset.jpg' %}" alt="Password Reset Image" style="height: 80%;">
                </div>
            </div>
        </div>
    </div>
</main>

<script>
    $(document).ready(function(){
        $('.pass_show').append('<span class="ptxt">Show</span>');  
        });
    
        $(document).on('click','.pass_show .ptxt', function(){ 

        $(this).text($(this).text() == "Show" ? "Hide" : "Show"); 

        $(this).prev().attr('type', function(index, attr){return attr == 'password' ? 'text' : 'password'; });
    });  
</script>

{% endblock content %}

templates/userauths/password_reset_invalid.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main pages">
    <div class="page-header breadcrumb-wrap">
		<div class="container">
			<div class="breadcrumb">
				<a href="{% url 'OCS_APP:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
				<span></span> Login <span></span> Password Reset Invalid
			</div>
		</div>
	</div>

    <div class="page-content pt-60 pb-60 d-flex justify-content-center align-items-center">
        <img src="{% static 'assets/imgs/page/expired.jpg' %}" alt="Link Expired Image">
    </div>
</main>

{% endblock content %}

templates/userauths/profile-edit.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'OCS_APP:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Pages <span></span> My Account
            </div>
        </div>
    </div>
    
    <div class="page-content pt-60 pb-60">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="dashboard-menu">
                                <ul class="nav flex-column" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><i class="fi-rs-user mr-10"></i>Profile</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'userauths:log-out' %}"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="tab-content account dashboard-content pl-50">
                                <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                    <div class="card">
                                        <div class="card-header border-bottom">
                                            <h3 class="mb-0">Update Profile</h3>
                                        </div>
                                        {% if form.errors %}
                                            <div class="alert-danger alert">
                                                <strong>{{form.errors}}</strong>
                                            </div>
                                        {% endif %}
                                        <div class="card-body mb-2" style="display: flex; align-items: center; gap: 10px;">
                                            <div>
                                                {% if profile.image %}
                                                    <span><img src="{{profile.image.url}}" alt="Profile Image" style="width: 150px; object-fit: cover; border-radius: 50%; height: 150px;"></span>
                                                {% else %}
                                                    <span><img src="https://prephoops.com/wp-content/uploads/sites/2/user-uploads/26BD0621-0176-4C16-BB71-E008281DD78F.png" alt="Profile Image" style="width: 150px; object-fit: cover; border-radius: 50%; height: 150px;"></span>
                                                {% endif %}
                                            </div>
                                            <div>
                                                <form method="POST" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="mb-3">
                                                        {{form.full_name}}
                                                    </div>
                                                    <div class="mb-3">
                                                        {{form.bio}}
                                                    </div>
                                                    <div class="mb-3">
                                                        {{form.phone}}
                                                    </div>
                                                    <div class="mb-3">
                                                        {{form.image}}
                                                    </div>
                                                    <button class="btn btn-success" style="border: none;" type="submit">Save Changes</button>
                                                </form>
                                            </div> 
                                        </div>
                                        </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/userauths/register.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main pages">
    <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Register Account
                </div>
            </div>
    </div>

    <div class="page-content pt-60 pb-60">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        {% if form.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{form.errors}}</strong>
                                        </div>
                                        {% endif %}
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Create an Account</h1>
                                            <p class="mb-30">Already have an account? <a href="{% url 'userauths:log-in' %}">Login</a></p>
                                        </div>
                                        <form method="post">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                {{form.username}}
                                            </div>
                                            <div class="form-group">
                                                {{form.User_Email}}
                                            </div>
                                            <div class="form-group">
                                                {{form.password1}}
                                            </div>
                                            <div class="form-group">
                                                {{form.password2}}
                                            </div>
                                            <!--<div class="form-group">
                                                <input type="text" required="" name="username" placeholder="Username" />
                                            </div>
                                            <div class="form-group">
                                                <input type="text" required="" name="email" placeholder="Email" />
                                            </div>
                                            <div class="form-group">
                                                <input required="" type="password" name="password" placeholder="Password" />
                                            </div>
                                            <div class="form-group">
                                                <input required="" type="password" name="password" placeholder="Confirm password" />
                                            </div>
                                            <div class="login_footer form-group">
                                                <div class="chek-form">
                                                    <input type="text" required="" name="email" placeholder="Security code *" />
                                                </div>
                                                <span class="security-code">
                                                    <b class="text-new">8</b>
                                                    <b class="text-hot">6</b>
                                                    <b class="text-sale">7</b>
                                                    <b class="text-best">5</b>
                                                </span>
                                            </div>
                                            <div class="payment_option mb-50">
                                                <div class="custome-radio">
                                                    <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios3" checked="" />
                                                    <label class="form-check-label" for="exampleRadios3" data-bs-toggle="collapse" data-target="#bankTranfer" aria-controls="bankTranfer">I am a customer</label>
                                                </div>
                                                <div class="custome-radio">
                                                    <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4" checked="" />
                                                    <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#checkPayment" aria-controls="checkPayment">I am a vendor</label>
                                                </div>
                                            </div>
                                            <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox12" value="" />
                                                        <label class="form-check-label" for="exampleCheckbox12"><span>I agree to terms &amp; Policy.</span></label>
                                                    </div>
                                                </div> 
                                                <a href="page-privacy-policy.html"><i class="fi-rs-book-alt mr-5 text-muted"></i>Lean more</a>
                                            </div> -->
                                            <div class="form-group mb-30">
                                                <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold" name="login">Submit &amp; Register</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <div class="card-login mt-115" style="border: none;">
                                    <img src="{% static 'assets/imgs/page/register.png' %}" alt="Register Image">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</main>

{% endblock content %}