OCS_APP/urls.py
from django.urls import path
from OCS_APP import views

app_name = 'OCS_APP'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/', views.category_list_view, name='category-list'),
    path('category/<cid>/', views.category_products_list_view, name='category-product-list'),
    path('product/<pid>/', views.product_detail_view, name='product-detail'),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('search/', views.search_view, name='search'),
    path('cart/', views.cart_view, name='cart'),
    path('delete-from-cart/', views.delete_item_from_cart, name='delete-from-cart'),
    path('update-cart/', views.update_cart, name='update-cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('payment-completed/<inv_id>/<pay_method>/', views.payment_completed_view, name='payment-completed'),
    path('payment-failed/', views.payment_failed_view, name='payment-failed'),
    path('dashboard/', views.customer_dashboard, name='dashboard'),
    path('dashboard/order/<int:id>', views.order_detail, name='order-detail'),
    path('contact-us/', views.contact_us, name='contact-us'),
    path('products/tag/<slug:tag_slug>/', views.tag_list, name='tags'),
    path('make-default-address/', views.make_address_default, name='make-default-address'),
    path('delete-address/', views.delete_address, name='delete-address'),
    path('shop/', views.shop_view, name='shop'),
    path('add-review/<int:pid>/', views.ajax_add_review, name='add-review'),
    
    path('my/', views.my, name='my'),
]

handler404 = 'OCS_APP.views.custom_404_view'

Oral_Care_Solution/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('OCS_APP.urls')),
    path('user/', include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path('log-in/', views.login_view, name='log-in'),
    path('log-out/', views.logout_view, name='log-out'),
    path('register/', views.register_view, name='register'),
    path('profile/update/', views.profile_update, name='profile-update'),
    path('forget-password/', views.forgot_password, name='forgot_password'),
    path('get-reset-password-email/', views.get_reset_password_email, name='get_reset_password_email'),
    path('reset/<str:uidb64>/<str:token>/', views.reset_password, name='reset_password'),
]

templates/cart.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main" id="cart-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'OCS_APP:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Cart
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Your Cart</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand cart-items-count">{{totalcartitems}}</span> product{{totalcartitems|pluralize}} in your cart</h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist" style="text-align: center;">
                            <thead>
                                <tr class="main-heading">
                                    <th scope="col" style="text-align: center;" class="start">Product</th>
                                    <th scope="col" style="text-align: center;">Title</th>
                                    <th scope="col" class="text-center" style="text-align: center;">Quantity</th>
                                    <th scope="col" style="text-align: center;">Subtotal</th>
                                    <th scope="col" style="text-align: center;" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product_id, item in cart_data.items %}
                                    <tr class="pt-30 cart-item">
                                        <td class="image product-thumbnail pt-40" style="text-align: center;"><img src="{{item.image}}" alt="#"></td>
                                        <td class="product-des product-name" style="text-align: center;">
                                            <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'OCS_APP:product-detail' item.pid %}">{{item.title}}</a></h6>
                                        </td>
                                        <td class="text-center detail-info" style="text-align: center;">
                                            <div>
                                                <button type="button" onclick="decrementValue('item{{ forloop.counter }}')" class="buttonali update-product" data-product="{{product_id}}">-</button>
                                                <input type="number" id="item{{ forloop.counter }}" name="quantity" value="{{item.qty}}" min="1" class="quantityInput product-qty-{{product_id}}" readonly>
                                                <button type="button" onclick="incrementValue('item{{ forloop.counter }}', {{ item.max_stock_product }})" class="buttonali update-product" data-product="{{product_id}}">+</button>
                                            </div>
                                        </td>
                                        <td class="price" data-title="Price" style="text-align: center;">
                                            <h6 class="product-price product-price-{{ product_id }}">Rs {% widthratio item.price 1 item.qty %}</h6>
                                        </td>
                                        <td class="action text-center" data-title="Remove" style="text-align: center;"><button style="border: none; background: none;" class="text-body delete-product" data-product="{{product_id}}"><i class="fi-rs-trash"></i></button></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                
                <div class="col-lg-4">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <table class="table no-border">
                                <tbody>
                                  
                                    <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Shipping</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">Free</h4</td> </tr> <tr>
                                        </tr> <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Total</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end updatedcarttotal">Rs {{cart_total_amount}}</h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    
                            <a href="{% url 'OCS_APP:checkout' %}" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></a>
                        
                    </div>
                </div>
                
            </div>
        </div>
</main>

{% endblock content %}

templates/category-list.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main">
    <div class="page-header mt-30 mb-75">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-4">
                            <h1 class="mb-15">{{categories.count}} Categor{{categories.count|pluralize:"y,ies"}}</h1>
                            <div class="breadcrumb">
                                <a href="{% url 'OCS_APP:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> Categor{{categories.count|pluralize:"y,ies"}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>

    <div class="page-content mb-50">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <div class="loop-grid pr-30">
                            <div class="row">
                                {% for i in categories %}
                                    <article class="col-xl-4 col-lg-6 col-md-6 text-center hover-up mb-30 animated">
                                        <div class="post-thumb">
                                            <a href="{% url 'OCS_APP:category-product-list' i.cid %}">
                                                <img class="border-radius-15" src="{{i.image.url}}" alt="Category Image">
                                            </a>
                                        </div>
                                        <div class="entry-content-2">
                                            <!--   <h6 class="mb-10 font-sm"><a class="entry-meta text-muted" href="blog-category-grid.html">Side Dish</a></h6> -->
                                            <h4 class="post-title mb-15">
                                                <a href="{% url 'OCS_APP:category-product-list' i.cid %}">{{i.title}}</a>
                                            </h4>
                                            <div class="entry-meta font-xs color-grey mt-10 pb-10">
                                                <div>
                                                    <span class="hit-count mr-10">{{products_count}} Product{{products_count|pluralize}}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </article>
                                {% endfor %}
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</main>
   
{% endblock content %}  

templates/category-product-list.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main">
        <div class="page-header mt-30 mb-50">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-6">
                            <h1 class="mb-15">{{category.title}}</h1>
                            <div class="breadcrumb">
                                <a href="{% url 'OCS_APP:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> Categories <span></span> {{category.title}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mb-30">
            <div class="row">
                <div class="col-12">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We found <strong class="text-brand">{{products.count}}</strong> item{{products.count|pluralize}} for you!</p>
                        </div>   
                    </div>
                    <div class="row product-grid">
                        {% for i in products %}
                            <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                                    <div class="product-cart-wrap mb-30 wow animate__animated animate__fadeIn" data-wow-delay=".1s">
                                        <div class="product-img-action-wrap">
                                            <div class="product-img product-img-zoom">
                                                <a href="{% url 'OCS_APP:product-detail' i.pid %}">
                                                    <img class="default-img" src="{{i.image.url}}" alt="Product Image" />
                                                    <img class="hover-img" src="{{i.image.url}}" alt="" />
                                                </a>
                                            </div>
                                            <div class="product-badges product-badges-position product-badges-mrg">
                                                <span class="hot"><strong>-{{i.get_percentage|floatformat:0}}% off</strong></span>
                                            </div>
                                        </div>
                                        <div class="product-content-wrap">
                                            <div class="product-category">
                                                <a href="{% url 'OCS_APP:product-detail' i.pid %}">{{i.category.title}}</a>
                                            </div>
                                            <h2><a href="{% url 'OCS_APP:product-detail' i.pid %}">{{i.title}}</a></h2>
                                            <div class="product-rate-cover">
                                                <div class="product-rate d-inline-block">
                                                    <div class="product-rating" style="width: 90%"></div>
                                                </div>
                                                <span class="font-small ml-5 text-muted"> (4.0)</span>
                                            </div>
                                            <div>
                                                <span class="font-small text-muted">By <a href="{% url 'OCS_APP:product-detail' i.pid %}">{{i.vendor.title}}</a></span>
                                            </div>
                                            <div class="product-card-bottom">
                                                <div class="product-price">
                                                    <span>Rs</span><span class="current-product-price-{{i.id}}">{{i.price}}</span><br>
                                                    <span class="old-price">Rs {{i.old_price}}</span>
                                                </div>
                                                <div class="add-cart">
                                                    <input type="hidden" value="1" class="product-quantity-{{i.id}}" id="product-quantity">
                                                    <input type="hidden" class="product-pid-{{i.id}}" value="{{i.pid}}">
                                                    <input type="hidden" class="product-image-{{i.id}}" value="{{i.image.url}}">
                                                    <input type="hidden" class="product-id-{{i.id}}" value="{{i.id}}">
                                                    <input type="hidden" class="product-title-{{i.id}}" value="{{i.title}}">
                                                    <button class="add add-to-cart-btn" id="add-to-cart-btn" data-index="{{i.id}}" style="border: none;"><i class="fi-rs-shopping-cart mr-5"></i>Add</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        {% endfor %}
                        <!--end product card-->
                    </div>
                </div>
            </div>
        </div>
</main>

{% endblock content %}

templates/dashboard.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'OCS_APP:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        
        <div class="page-content pt-60 pb-60">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 m-auto">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="dashboard-menu">
                                    <ul class="nav flex-column" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><i class="fi-rs-user mr-10"></i>Profile</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="dashboard-tab" data-bs-toggle="tab" href="#dashboard" role="tab" aria-controls="dashboard" aria-selected="false"><i class="fi-rs-settings-sliders mr-10"></i>Dashboard</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="orders-tab" data-bs-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="false"><i class="fi-rs-shopping-bag mr-10"></i>Orders</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'userauths:log-out' %}"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="tab-content account dashboard-content pl-50">
                                    <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <div class="card">
                                            <div class="card-header border-bottom">
                                                <h3 class="mb-0">My Profile</h3>
                                            </div>
                                            <div class="card-body mb-2" style="display: flex; align-items: center; gap: 10px;">
                                                <div>
                                                    {% if profile.image %}
                                                        <span><img src="{{profile.image.url}}" alt="Profile Image" style="width: 150px; object-fit: cover; border-radius: 50%; height: 150px;"></span>
                                                    {% else %}
                                                        <span><img src="https://prephoops.com/wp-content/uploads/sites/2/user-uploads/26BD0621-0176-4C16-BB71-E008281DD78F.png" alt="Profile Image" style="width: 150px; object-fit: cover; border-radius: 50%; height: 150px;"></span>
                                                    {% endif %}
                                                </div>
                                                <div>
                                                    <span><input class="mb-2" type="text" value="Name: {{profile.full_name}}" readonly></span>
                                                    <span><input class="mb-2" type="text" value="Bio: {{profile.bio}}" readonly></span>
                                                    <span><input class="mb-2" type="text" value="Phone: {{profile.phone}}" readonly></span>
                                                    {% if profile.verified == True %}
                                                        <div class="p-4 border-rounded">
                                                            <span>Verified: </span><span><i class="fas fa-check"></i></span>
                                                        </div>
                                                    {% else %}
                                                        <div class="p-4 border-rounded">
                                                            <span>Not verified: </span><span><i class="fa fa-times"></i></span>
                                                        </div>
                                                    {% endif %}
                                                    <div class="p-4 border-rounded">
                                                        <a href="{% url 'userauths:profile-update' %}" class="btn btn-success" style="border: none;">Edit Profile</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="dashboard" role="tabpanel" aria-labelledby="dashboard-tab">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="mb-0">Orders Statistics</h3>
                                            </div>
                                            <div class="card-body">
                                               
                                            </div>
                                            <div>
                                                <canvas id="myChart" style="height: 50px;"></canvas>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="orders" role="tabpanel" aria-labelledby="orders-tab">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="mb-0">Your Orders</h3>
                                            </div>
                                            <div class="card-body">
                                                <div class="table-responsive">
                                                    <table class="table">
                                                        <thead>
                                                            <tr>
                                                                <th>Order</th>
                                                                
                                                                <th>Date</th>
                                                                <th>Status</th>
                                                                <th>Paid Status</th>
                                                                <th>Total</th>
                                                                <th>Actions</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for o in orders_list %}
                                                                <tr>
                                                                    <td>INVOICE#{{o.id}}</td>
                                                                    <td>{{o.order_date}}</td>
                                                                    <td>{{o.product_status|title}}</td>
                                                                    {% if o.paid_status == True %}
                                                                        <td class="text-success"><b>&#10004</b></td>
                                                                    {% else %}
                                                                        <td class="text-danger"><b><span>X</span></b></td>
                                                                    {% endif %}
                                                                    <td>{{o.price}}</td>
                                                                    <td><a href="{% url 'OCS_APP:order-detail' o.id %}" class="btn-small d-block">View</a></td>
                                                                </tr>
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</main>

<script>
    const labels = {{ month|safe }};
    const data = {
        labels: labels,
        datasets: [{
            label: 'Number of orders per month',
            backgroundColor: 'rgb(59, 183, 126)',
            borderColor: 'rgb(59, 183, 126)',
            data: {{ total_orders|safe }}
        }]
    };

    const config = {
        type: 'bar',
        data: data,
        options: {
            scales: {
                y: {
                    ticks: {
                        precision: 0, // Specify zero decimal places
                        stepSize: 1 // Specify step size as 1 to show only integer values
                    }
                }
            }
        }
    };

    const myChart = new Chart(
        document.getElementById('myChart'),
        config
    );
</script>

{% endblock content %}

templates/order_confirmation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Confirmation</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f8f8;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #333;
        }
        .order-details {
            border-top: 1px solid #ccc;
            padding-top: 20px;
            margin-top: 20px;
        }
        .order-details ul {
            list-style-type: none;
            padding: 0;
        }
        .order-details ul li {
            margin-bottom: 10px;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Order Confirmation</h1>
            <p>Thank you for your order!</p>
            <p>Company Name</p>
        </div>
        <div class="order-details">
            <p>Dear {{ name }},</p>
            <p>Thank you for your order. Below are the details:</p>
            <ul>
                {% for i in order_items %}
                    <li>{{ i.item }} - Quantity: {{ i.qty }} - Price: {{ i.price }}</li>
                {% endfor %}
            </ul>
            <p>Total amount: Rs {{ total }}</p>
            <p>Shipping address: {{active_address.address}}</p>
            <p>Payment method: {{ pay_method }}</p>
        </div>
        <div class="footer">
            <p>Thank you for shopping with us!</p>
        </div>
    </div>
</body>
</html>

templates/payment-failed.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<main class="main page-404">
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto text-center">
                        <p class="mb-20"><img src="{% static 'assets/imgs/page/failed.jpg' %}" alt="" class="hover-up" /></p>
                        <h1 class="display-2 mb-30">Payment Failed</h1>
                        <p class="font-lg text-grey-700 mb-30">
                            Try Again Later
                        </p>
                        <a class="btn btn-default submit-auto-width font-xs hover-up mt-30" href="{% url 'OCS_APP:index' %}"><i class="fi-rs-home mr-5"></i> Back To Home Page</a>
                    </div>
                </div>
            </div>
        </div>
</main>

{% endblock content %}